version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
    - IS_DOCKER=true
    volumes:
      - .:/usr/src/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
